### ISSUE TITLE
Generate certificate for RSP-Test

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/rsp-uk-docs#73]
Since cert-manager is not available yet, for this test version lets create a certificate for the Domain name that we'll be using for the test version:

Steps will be something like this:
- Create NGINX server
- Point Domain name to IP of the NGINX server
- Install & run certbot
- Copy key & full chain, and copy it to the VAULT service (./generate_secrets script in phalanx)

**Comment by gpfrancis** [comment]
First part done. Cert files temporarily in /home/ubuntu/rsp-test_certs on the vault server.

**Comment by stvoutsin** [comment]
The cert is now included in the Vault service, and used by the newly deployed service https://rsp-test.lsst.ac.uk
