### ISSUE TITLE
Enable butler default account for the RSP

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/rsp-uk-docs#75]
There are several references to a butler account/secret in Phalanx, and there is a way to enable a generic/shared butler account to be enabled in Jupyter environments for all users. We need to figure out where this needs to be set & enable it

Jupyter Logs:
2023-05-18T13:24:42Z [Warning] MountVolume.SetUp failed for volume "butler-secret" : secret "butler-secret" not found

**Comment by aibsen** [comment]
we enables a readonly user for the butler a while ago
